# sudo -i 
# curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
zookeeper:
  image: qa.stratio.com:5000/stratio/zookeeper:3.4.6
  container_name: zookeeper
  ports:
    - "2181:2181"

waitzk:
  image: aanand/wait
  container_name: waitzk
  links:
    - zookeeper

kafka:
  image: qa.stratio.com:5000/kafka:0.8.1.1
  container_name: kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper
    - waitzk
  environment:
    ZK_CONNECT: zookeeper:2181

waitkafka:
  image: aanand/wait
  container_name: waitkafka
  links:
    - kafka

cassandra-lucene-index:
  image: qa.stratio.com:5000/stratio/cassandra-lucene-index:2.2.4.0
  container_name: cassandra
  ports: 
    - "9042:9042"
  environment:
   CLUSTER_NAME: DemoCluster
   MAX_HEAP: 256M
   MAX_NEW: 64M
   SEEDS: 127.0.0.1

waitcassandra:
  image: aanand/wait
  container_name: waitcassandra
  links:
    - cassandra-lucene-index

elasticsearch:
  image: qa.stratio.com:5000/stratio/elasticsearch:1.7.1
  container_name: elasticsearch
  ports: 
    - "9300:9300"
    - "9200:9200"

waitelastic:
  image: aanand/wait
  container_name: waitelasticsearch
  links:
    - elasticsearch


ingestion:
  image: qa.stratio.com:5000/stratio/ingestion:latest
  container_name: ingestion
  links:
    - elasticsearch
    - waitelastic
    - waitcassandra  
    - cassandra-lucene-index 

decision:
  image: qa.stratio.com:5000/stratio/decision:latest
  container_name: decision
  links:
    - zookeeper
    - kafka
    - waitkafka
    - elasticsearch
    - waitelastic
    - waitcassandra  
    - cassandra-lucene-index 
    - ingestion
  environment:
    KAFKA_HOSTS: kafka:9092
    ZOOKEEPER_HOSTS: zookeeper:2181
    ES_HOSTS: elasticsearch:9300
    CLUSTERING_ENABLED: "false"
    GROUP_ID: stratiogroup
    FAILOVER_ENABLED: "true"

decision-shell:
  image: qa.stratio.com:5000/stratio/decision-shell:latest
  container_name: shell
  links:
    - zookeeper
    - kafka
    - decision
  environment:
    KAFKA_HOSTS: kafka:9092
    ZOOKEEPER_HOSTS: zookeeper:2181